# -*- mode: ruby -*-
# vi: set ft=ruby :

# WIP: EXPERIMENTAL SCRIPTS!!! USE WITH CAUTION, OR DONT USE AT ALL :D!

# Sources:
# https://gist.github.com/santrancisco/a7183470efa0e3412222670d0bfb3da5
# Tero Karvinen Himself and; https://terokarvinen.com/2018/automatically-provision-vagrant-virtualmachines-as-salt-slaves/
# Niko Heiskanen: https://heiskanen.rocks/server_management/h1 

# Provision Debian
$minion1 = <<MINION1
apt update -y
sudo apt install bash-completion -y
apt install salt-minion -qy
sed -i 's/\#master\:.*/master\:\ 192.168.56.1/g' /etc/salt/minion
systemctl restart salt-minion
MINION1

# Provision Fedora
$minion2 = <<MINION2
dnf check-update -y
sudo dnf install bash-completion -y
dnf install salt-minion -qy
sed -i 's/\#master\:.*/master\:\ 192.168.56.1/g' /etc/salt/minion
systemctl restart salt-minion
MINION2

# Provision Windows
$minion3 = <<MINION3
echo Installing Salt-Minion.
echo This will take a while, so dont worry!
powershell.exe -Command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; 
Invoke-WebRequest -Uri 'https://repo.saltproject.io/windows/Salt-Minion-3004.2-1-Py3-AMD64.msi' -OutFile 'C:/Users/IEUser/Salt-Minion-3004.2-1-Py3-AMD64.msi';
msiexec /i Salt-Minion-3004.2-1-Py3-AMD64.msi /quiet /norestart MASTER=192.168.56.1 MINION_ID=WindowsMinion"
waitfor WINDOWStoConfigureSalt /t 30 2>NUL
echo Done!
MINION3

Vagrant.configure(2) do |config|
  # Debian
  config.vm.define "Debian" do |debian|
    debian.vm.box = "debian/bullseye64"
    debian.vm.hostname = "debian-vagrant"
    debian.vm.network :private_network, ip: "192.168.56.201"
    debian.vm.provision "shell", inline: $minion1
	debian.vm.synced_folder '.', '/vagrant', disabled: true
    debian.vm.provider :virtualbox do |vb|
      vb.name = "Debian - Vagrant"
	  vb.memory = 1028
      vb.cpus = 2
	  vb.customize ["modifyvm", :id, "--vram", "16"]
    end
  end
  # Fedora
  config.vm.define "Fedora" do |fedora|
    fedora.vm.box = "fedora/36-cloud-base"
    fedora.vm.hostname = "fedora-vagrant"
    fedora.vm.network :private_network, ip: "192.168.56.202"
    fedora.vm.provision "shell", inline: $minion2
	fedora.vm.synced_folder '.', '/vagrant', disabled: true
    fedora.vm.provider :virtualbox do |vb|
      vb.name = "Fedora - Vagrant"
	  vb.memory = 1028
      vb.cpus = 2
	  vb.customize ["modifyvm", :id, "--vram", "16"]
    end 
  end
  # Windows...
  config.vm.define "Windows" do |window|  

  # Basic
	window.vm.box = "Microsoft/EdgeOnWindows10"
	window.vm.guest = :windows 
	window.vm.synced_folder '.', '/vagrant', disabled: true

  # Network
	window.vm.network :private_network, ip: "192.168.56.203", auto_config: false
	
  # Config SSH
	window.ssh.username="IEUser"
	window.ssh.password="Passw0rd!"
	window.ssh.insert_key = false
	window.ssh.sudo_command = ''
	window.ssh.shell = 'sh -l'

  # Machine stuff
    window.vm.provider :virtualbox do |vb|
      vb.name = "Windows - Vagrant"
	  vb.memory = 4096
      vb.cpus = 2
	  vb.customize ["modifyvm", :id, "--vram", "256"]
	end

  # Install and configure Salt-Minion
  	window.vm.provision "shell", privileged: false, inline: $minion3
	end
end
